{
 "title": "历史数据分析",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "order",
    "query": "select table_name from information_schema.tables where table_schema='ns_data'"
   }
  ]
 },
 "panels": [
  {
   "title": "日成交额走势",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  \n  timestamp(DATE_FORMAT(order_time,\"%Y-%m-%d\")),\n  sum(notional)\n  \nFROM $order\nWHERE\n  order_status = 'FILLED'\ngroup by timestamp(DATE_FORMAT(order_time,\"%Y-%m-%d\"))\n"
    }
   ]
  },
  {
   "title": "今日成交总额",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  sum(notional)\n\nFROM $order\nWHERE\n  order_status = 'FILLED' and order_time > curdate()\nORDER BY time"
    }
   ]
  },
  {
   "title": "日PNL",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  \n  DATE_FORMAT(order_time,\"%Y-%m-%d\"),\n  sum(cast(profit as DECIMAL(5)))\n  \nFROM $order\nWHERE\n  order_status = 'FILLED'\ngroup by DATE_FORMAT(order_time,\"%Y-%m-%d\")\n"
    }
   ]
  },
  {
   "title": "历史成交总额",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  sum(notional)\n\nFROM $order\nWHERE\n  order_status = 'FILLED'\nORDER BY time"
    }
   ]
  },
  {
   "title": "今日成交币种分布",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  symbol,\n  sum(notional)\n\nFROM $order\nWHERE\n  order_status = 'FILLED' and time >curdate()\ngroup BY symbol"
    }
   ]
  },
  {
   "title": "今日下单金额多空比",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  sum(notional),\n  side\n  \nFROM $order\nWHERE\n  order_status = 'FILLED' and order_time>curdate()\ngroup BY side"
    }
   ]
  }
 ]
}