{
 "title": "实时持仓",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "position",
    "query": "select table_name from information_schema.tables where table_schema='ns_data'"
   },
   {
    "name": "order",
    "query": "select table_name from information_schema.tables where table_schema='ns_data'"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  sum(unrealizedProfit) AS \"未实现盈亏\",\n  count(symbol) AS \"持仓币种数量\",\n  avg(all_cash) AS \"账户实时余额\"\nFROM $position\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "今日实时成交明细",
   "type": "table",
   "gridPos": { "h": 21, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  order_time AS 订单时间,\n  symbol AS 币种,\n  order_price AS 下单价格,\n  filled_price AS 成交均价,\n  order_quantity AS 下单数量,\n  filled_quantity AS 成交数量,\n  notional AS 成交金额,\n  order_status AS 订单状态\n  \nFROM $order\n\nWHERE order_time >=curdate()\n\nORDER BY time"
    }
   ]
  },
  {
   "title": "做空仓位",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  sum(unrealizedProfit) AS \"unrealizedProfit\",\n  count(symbol),\n  sum(notional)\nFROM $position\nWHERE\n  notional <= 0\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "做多仓位",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(time,$__interval),\n  sum(unrealizedProfit) AS \"unrealizedProfit\",\n  count(symbol),\n  sum(notional)\nFROM $position\nWHERE\n  notional >= 0\nGROUP BY 1\nORDER BY $__timeGroup(time,$__interval)"
    }
   ]
  },
  {
   "title": "当前仓位",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "SELECT\n  time AS \"time\",\n  side,\n  symbol,\n  unrealizedProfit,\n  notional,\n  account\nFROM $position\nORDER BY time"
    }
   ]
  }
 ]
}