{
 "title": "实时下单分析",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "order",
    "query": "select table_name from information_schema.tables where table_schema='ns_data'"
   }
  ]
 },
 "panels": [
  {
   "title": "今日成交金额走势",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  $__timeGroupAlias(order_time,$__interval),\n  notional\n  \nFROM $order\nWHERE\n  order_status = 'FILLED' and order_time>curdate()\n"
    }
   ]
  },
  {
   "title": "当前小时下单金额",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  symbol,\n  sum(notional) \n  \nFROM $order\nWHERE\n  order_status = 'FILLED' and DATE_SUB(NOW(), INTERVAL 1 HOUR) <= time\ngroup BY symbol"
    }
   ]
  },
  {
   "title": "当前小时成交额",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  sum(notional)\n\nFROM $order\nWHERE\n  order_status = 'FILLED' and DATE_SUB(NOW(), INTERVAL 1 HOUR) <= time\nORDER BY time"
    }
   ]
  },
  {
   "title": "今日成交总额",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n\n  sum(notional)\n\nFROM $order\nWHERE\n  order_status = 'FILLED' and order_time > curdate()\nORDER BY time"
    }
   ]
  },
  {
   "title": "当前小时下单金额多空比",
   "type": "piechart",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  \n  sum(notional),\n  side\n  \nFROM $order\nWHERE\n  order_status = 'FILLED' and DATE_SUB(NOW(), INTERVAL 1 HOUR) <= time\ngroup BY side"
    }
   ]
  },
  {
   "title": "当前小时下单币种",
   "type": "stat",
   "gridPos": { "h": 4, "w": 13, "x": 11, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  side,\n  symbol\n  \nFROM $order\nWHERE\n order_status = 'FILLED' and DATE_SUB(NOW(), INTERVAL 1 HOUR) <= time\n"
    }
   ]
  },
  {
   "title": "时PNL",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 18, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT\n\nDATE_FORMAT(order_time,\"%Y-%m-%d %H:00\") as order_time_h,\nsum(cast(profit AS DECIMAL(5)))\n\n\nFROM $order\nWHERE\norder_status = 'FILLED' and time >curdate()\ngroup by order_time_h"
    }
   ]
  },
  {
   "title": "当前小时下单明细",
   "type": "table",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(order_time,$__interval),\n  symbol,\n  side,\n  notional\n\n\n\nFROM $order\nWHERE\n  order_status = 'FILLED' and DATE_SUB(NOW(), INTERVAL 1 HOUR) <= time\nORDER BY order_time"
    }
   ]
  }
 ]
}